### ISSUE TITLE
Crystal 0.27.0 support

### ISSUE THREAD

**Issue by jwoertink** [akiicat/m3u8#3]
In this version of crystal, the `epoch` method was renamed to `to_unix` https://github.com/crystal-lang/crystal/blob/master/CHANGELOG.md#time

That's called [here](https://github.com/akiicat/m3u8/blob/master/src/m3u8/time_item.cr#L70) and [here](https://github.com/akiicat/m3u8/blob/master/src/m3u8/time_item.cr#L48)

**Comment by akiicat** [comment]
Thanks! 
Closed #4
