### ISSUE TITLE
Crystal 0.35 compatibility

### ISSUE THREAD

**Issue by jwoertink** [akiicat/m3u8#5]
https://github.com/akiicat/m3u8/blob/46c7243c72f3cef8226a8b118472853dece834c7/src/m3u8/concern.cr#L55-L62

For the next release, all case statements will need to have an `else` clause or be fully exhaustive otherwise it won't compile. 

```
In lib/m3u8/src/m3u8/concern.cr:55:7

 55 | case value
      ^
Error: case is not exhaustive.

Missing cases:
 - Nil
```

**Comment by akiicat** [comment]
Merged. I appreciate your contribution.
